# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.18.1
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# For details on what the tsv files in the Unsplash dataset contain, check [this link](https://github.com/unsplash/datasets/blob/master/DOCS.md)

# %%
# cd ..

# %%
import pandas as pd

# %% [markdown]
# ## 1 - photos.tsv
#
# The `photos.tsv` dataset has one row per photo. It contains properties of the photo, the name of the contributor, the image URL, and overall stats.
#
# | Field                       | Description |
# |-----------------------------|-------------|
# | photo_id                       | ID of the Unsplash photo |
# | photo_url                      | Permalink URL to the photo page on unsplash.com |
# | photo_image_url                | URL of the image file. Note: this is a [dynamic URL](https://unsplash.com/documentation#dynamically-resizable-images), so you can apply [resizing and customization operations directly on the image](https://unsplash.com/documentation#supported-parameters) |
# | photo_submitted_at             | Timestamp of when the photo was submitted to Unsplash |
# | photo_featured                 | Whether the photo was promoted to the [Editorial feed](https://unsplash.com/) or not |
# | photo_width                    | Width of the photo in pixels |
# | photo_height                   | Height of the photo in pixels |
# | photo_aspect_ratio             | Aspect ratio of the photo |
# | photo_description              | Description of the photo written by the photographer |
# | photographer_username          | Username of the photographer on Unsplash |
# | photographer_first_name        | First name of the photographer |
# | photographer_last_name         | Last name of the photographer |
# | exif_camera_make               | Camera make (brand) extracted from the EXIF data |
# | exif_camera_model              | Camera model extracted from the EXIF data |
# | exif_iso                       | ISO setting of the camera, extracted from the EXIF data |
# | exif_aperture_value            | Aperture setting of the camera, extracted from the EXIF data |
# | exif_focal_length              | Focal length setting of the camera, extracted from the EXIF data |
# | exif_exposure_time             | Exposure time setting of the camera, extracted from the EXIF data |
# | photo_location_name            | Location of the photo |
# | photo_location_latitude        | Latitude of the photo |
# | photo_location_longitude       | Longitude of the photo |
# | photo_location_country         | Country where the photo was made |
# | photo_location_city            | City where the photo was made |
# | stats_views                    | Total # of times that a photo has been viewed on the Unsplash platform |
# | stats_downloads                | Total # of times that a photo has been downloaded via the Unsplash platform |
# | ai_description                 | Textual description of the photo, generated by a 3rd party AI |
# | ai_primary_landmark_name       | Landmark present in the photo, generated by a 3rd party AI |
# | ai_primary_landmark_latitude   | Latitude of the landmark, generated by a 3rd party AI |
# | ai_primary_landmark_longitude  | Longitude of the landmark, generated by a 3rd party AI |
# | ai_primary_landmark_confidence | Landmark confidence of the 3rd party AI |
# | blur_hash                      | [BlurHash](https://blurha.sh/) hash of the photo |

# %%
photos = pd.read_csv("./data/unsplash-research-dataset-lite-latest/photos.tsv000", sep='\t', header=0)

# %%
photos.head()

# %%
len(photos)

# %%
photos["photo_description"].isna().mean()

# %% [markdown]
# ## 2 - keywords.tsv
#
# The `keywords.tsv` dataset has one row per photo-keyword pair. It contains data
# about how a keyword is connected to a photo and the conversions of the photo our search engine for a particular keyword.
#
# | Field                         | Description |
# |-------------------------------|-------------|
# | photo_id                      | ID of the Unsplash photo |
# | keyword                       | Keyword or search term |
# | ai_service_1_confidence       | Confidence for the keyword from a 3rd party AI (0-100)|
# | ai_service_2_confidence       | Confidence for the keyword from another 3rd party AI (0-100)|
# | suggested_by_user             | Whether the keyword was added by a user (human) |

# %%
keywords = pd.read_csv("./data/unsplash-research-dataset-lite-latest/keywords.tsv000", sep='\t', header=0)

# %%
keywords.head(3)

# %%
keyword_counts = keywords["keyword"].value_counts()
keyword_counts.describe(percentiles=[0.25, 0.5, 0.75, 0.9])

# %%
keywords[["ai_service_1_confidence", "ai_service_2_confidence"]].describe(percentiles=[0.25, 0.5, 0.75, 0.9]).round(3)

# %%
keywords["photo_id"].value_counts().describe()

# %% [markdown]
# ### Conclusions
# - Tags
#     - Most photos have **dozens of keywords** (very complete info!)
#     - The vast majority of the tags (>50%) appear ONLY ONCE.
#     - Very few tags appear 100s of times, while others just a handful
#         - For common tags: Using embeddings might be useful
#         - For uncommon tags: Semantic embeddings might work better
# - AI evaluation:
#     - In terms of evaluation score, the **service 1** tends to be more restrictive, while **service 2** tends to be more optimistic.
#     - Also, for some reason **there are values from 0 to 1 and from 0 to 100 mixed** on **service 2**.

# %% [markdown]
# ## 3 - collections.tsv
#
# *Note: A collection on Unsplash is a user created grouping of photos. These are similar to boards on Pinterest and can often group photos in complex and creative ways.*
#
# The `collections.tsv` dataset has one row per photo-collection pair. Whenever a photo
# belongs to a collection created by a user, it will appear as one row. Each row describes
# when the photo was added to the collection and gives the title of the collection.
#
# | Field                         | Description |
# |-------------------------------|-------------|
# | photo_id                      | ID of the Unsplash photo |
# | collection_id                 | ID of the Unsplash collection containing the photo |
# | collection_title              | Title of the collection containing the photo |
# | photo_collected_at            | Timestamp of when the photo was added to the collection |

# %%
collections = pd.read_csv("./data/unsplash-research-dataset-lite-latest/collections.tsv000", sep='\t', header=0)

# %%
collections["photo_collected_at"] = pd.to_datetime(collections["photo_collected_at"], format="ISO8601")

# %%
collections.head(3)

# %%
collections["collection_id"].value_counts().describe()

# %%
collections["photo_collected_at"].describe()

# %% [markdown]
# ### Conclusions
# - Most collections contain only one photo
# - Photos seems to be more or less constantly distributed over time.

# %% [markdown]
# ## 4 - conversions.tsv
#
# *Note: a conversion is currently defined as a user selecting an image to download it.*
#
# The `conversions.tsv` dataset has one row per search conversion. The dataset tells you which photo has been downloaded for a search, the country of origin, and an anonymous identifier to indiciate the unique users. The data goes back up to 1 year before the release of each version of the dataset.
#
# | Field                         | Description |
# |-------------------------------|-------------|
# | converted_at                  | Timestamp of the conversion event |
# | conversion_type               | Type of conversion (`download` only for now) |
# | keyword                       | Keyword that was searched and led to the conversion |
# | photo_id                      | Photo ID of the photo that converted |
# | anonymous_user_id             | Anonymous user ID |
# | conversion_country            | Country code of the device geolocation |

# %%
conversions = pd.read_csv("./data/unsplash-research-dataset-lite-latest/conversions.tsv000", sep='\t', header=0)

# %%
conversions.head(3)

# %%
len(conversions)

# %%
conversions["conversion_type"].unique()

# %%
country_conversion = conversions["conversion_country"].value_counts(normalize=True)

# %%
country_conversion.cumsum()[:20]

# %%
conversions["anonymous_user_id"].value_counts().describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95])

# %%
keyword_conversion = conversions["keyword"].value_counts(normalize=True).cumsum()
keyword_conversion[:1000]

# %%
keyword_conversion.reset_index(drop=True).plot(logx=True)

# %% [markdown]
# ### Conclusions
# - The vast majority of users only convert once, therefore it's reasonable to think that making recommendations for specific users might yield very low additional performance.
# - The **top 20 countries** correspond to almost 75% of interactions.
# - The top keywords conversion yield a somewhat-logarithmic curve:
#     - Top 10 -> 13%
#     - Top 100 -> 40%
#     - Top 1000 -> 65%
#     - Top 1000 -> 83% 

# %% [markdown]
# ## 5 - colors.tsv
#
# *Note: The coverage and score data comes from a 3rd party AI*
#
# The `colors.tsv` dataset has one row per major color present in the photo. The dataset tells which colors are contained within a photo, their coverage as a percentage, and a score for how in focus the color is.
#
# | Field                     | Description |
# |---------------------------|-------------|
# | photo_id                  | ID of the Unsplash photo |
# | hex                       | Hexadecimal representation of the color |
# | red                       | Red component of the photo in the RGB system |
# | green                     | Green component of the photo in the RGB system |
# | blue                      | Blue component of the photo in the RGB system |
# | keyword                   | Name of the closest color as a [CSS color keyword](https://www.w3schools.com/cssref/css_colors.asp) |
# | coverage                  | Pixel coverage of the color as a percentage |
# | score                     | Score of the color in the photo (including the notion of focus) |

# %%
colors = pd.read_csv("./data/unsplash-research-dataset-lite-latest/colors.tsv000", sep='\t', header=0)

# %%
colors.head()

# %%
x = colors[colors["photo_id"]=="_0vH4E1YYsY"]
x

# %%
import matplotlib.pyplot as plt

# Replace these hex color values with your own
hex_colors = ["#" + code for code in x["hex"]]

# Create a figure and axis
fig, ax = plt.subplots(figsize=(len(hex_colors), 1))

# Plot each hex color as a rectangle
for i, color in enumerate(hex_colors):
    ax.add_patch(plt.Rectangle((i, 0), 1, 1, color=color))

# Set the x-axis labels to be the hex color values
ax.set_xticks(range(len(hex_colors)))
ax.set_xticklabels(hex_colors)

# Remove y-axis ticks and labels
ax.set_yticks([])
ax.set_yticklabels([])

# Set plot title and show the plot
plt.title('Hex Color Values')
plt.show()

# %%
